#!/usr/bin/env bash

timestamp=`date`
branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')

# build html and pdf
PANDOCARGS='--latex-engine=xelatex' make html
wkhtmltopdf ./index.html ./index.pdf

# commit changes to source
git add -A
git commit -m "update - {timestamp}"

# merge changes from source
git checkout gh-pages
git merge ${branch}

# deploy to gh-pages
git push origin gh-pages

# checkout to source branch
git checkout ${branch}
