#!/usr/bin/env bash

timestamp=`date`
branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')

git checkout gh-pages
git merge ${branch}
PANDOCARGS='--latex-engine=xelatex' make
git add -A
git commit -m "build - ${timestamp}"
git push origin gh-pages
git checkout ${branch}
